name: 04-Using Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run: working-directory: 04-using-actions/react-app #setting up the working dir in job level
                
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: setup Node
              uses: actions/setup-node@v4
              with: 
                node-version: '20.x'
            - name: Install Dependencies
              run: |
                npm install
                npm ci
              #working-directory: 04-using-actions/react-app  #setting up the working dir in step level
            - name: Run unit test
              run: npm run test