name: 06-Contexts
run-name: 06 - Context | DEFAULT ${{ inputs.debug }}
on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env:
  my_workflow_var: 'workflow'
  my_overwritten_var: 'workflow'

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      my_job_var: 'job'
      my_overwritten_var: 'job'

    steps:
      - name: Display information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number ${{ github.run_number }}"

      - name: Retrive variable
        run: | 
          echo "Variable value: ${{ vars.my_var }}"

      - name: Printing Env variable
        run: | 
          echo "This tha value of my_overwritten_var: ${{ env.my_overwritten_var }}"
          echo "This tha value of my_job_var: ${{ env.my_job_var }}"
          echo "This tha value of my_workflow_var: ${{ env.my_workflow_var }}"
