name: 08 - Using Variables
run-name: 08-Using variables
on:
 # push:
  workflow_dispatch:
env:  # Job var can overwrite Workflow var and step var can overwrite a job var.
  workflow_var: 'I am a workflow env var'
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      job_var: 'I am a job var'
    steps:
      - name: Print Env variable
        env:
          STEP_VAR: 'I am a step env var'
          step_var2: 'I am a another step env var'
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Another step env var: ${{ env.step_var2 }}"
          echo "Workflow env var: ${{ env.workflow_var }}"
          echo "Job env var: ${{ env.job_var }}"