name: 09-Using Fuctions
on: 
  Pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: exit 1
      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will  be print if previous steps succesd."
      - name: I will execute when failure
        if: ${{ failure() }}
        run: echo "I will prnt if any previous steps failes."
      - name: I will execute except cancelled
        if: ${{ !cancelled() }}
        run: echo "I'll always print, except when the workflow is cancelled." 
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I'll print when the workflow is cancelled." 